name: Docker Build and Push

on:
  push:
    branches:
      - main  # Trigger the workflow only on the 'main' branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the repository code
    - name: Checkout repository
      uses: actions/checkout@v2

    # Step 2: Log in to Docker Hub
    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}  # Docker Hub username from secrets
        password: ${{ secrets.DOCKER_PASSWORD }}  # Docker Hub password from secrets

    # Step 3: Set up Docker Buildx (needed for advanced Docker builds)
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    # Step 4: Cache Docker layers to speed up future builds
    - name: Cache Docker layers
      uses: actions/cache@v2
      with:
        path: /tmp/.buildx-cache
        key: ${{ runner.os }}-buildx-${{ github.sha }}
        restore-keys: |
          ${{ runner.os }}-buildx-

    # Step 5: Build the Docker image and push to Docker Hub
    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        context: .  # Path to your Docker context (current repository)
        push: true  # Push the built image to Docker Hub
        tags: vaidik100/demoproject:latest  # Replace with your Docker Hub username/repository name

